spring:
  datasource:
    url: ${SYSTEM_DB_URL}
    username: ${SYSTEM_DB_USERNAME}
    password: ${SYSTEM_DB_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${INTEGRATION_KEYCLOAK_EXTERNAL_URL}/realms/${INTEGRATION_KEYCLOAK_REALM}
  kafka:
    bootstrap-servers: ${INTEGRATION_KAFKA_BOOTSTRAP_SERVERS:http://localhost:1212}
    consumer:
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

logging:
  level:
    org:
      bazar: ${SYSTEM_LOGGING_LEVEL}

management:
  server:
    port: 8090

kafka:
  space-delete:
    topic: space.events.delete
    group-id: space-delete-group

service:
  bazar-persona:
    url: ${INTEGRATION_REST_BAZAR_PERSONA_API_URL}
  bazar-space:
    url: ${INTEGRATION_REST_BAZAR_SPACE_API_URL}

settings:
  scheduler:
    message:
      deleteMessages: ${SETTING_SCHEDULER_MESSAGE_DELETE_MESSAGES}
  message:
    replyPreviewLength: ${SETTING_MESSAGE_REPLY_PREVIEW_LENGTH}
  push-subscription:
    public-key: ${SETTING_PUSH_SUBSCRIPTION_PUBLIC_KEY}
    private-key: ${SETTING_PUSH_SUBSCRIPTION_PRIVATE_KEY}
    subject: ${SETTING_PUSH_SUBSCRIPTION_SUBJECT}