# Создай локально application-local.yaml и скопируй содержимое этого файла туда (если нужно, что-то поменяй).
# Не забудь добавить профиль local в конфигурацию запуска!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bazar_chat
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/local
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL:DEBUG}
service:
  bazar-persona:
    url: http://localhost:${service.bazar-persona.port}
    port: 8081
  authorization:
    port: 9090
    host: localhost
  bazar-space:
    url: http://localhost:${service.bazar-space.port}
    port: 8082

settings:
  scheduler:
    message:
      deleteMessages: "0 */5 * * * *"
  message:
    replyPreviewLength: 100
  push-subscription:
    public-key: <to generate>
    private-key: <to generate>
    subject: mailto:bazar@bazar.mail.ru